<?php
/**
 * Class that represents any error generated by the Database class
 *
 */
class DatabaseException extends Exception
{
	/**
	 * Stores the backtrace of this exception
	 *
	 * @var string
	 */
	protected $backtrace = "";
	/**
	 * Stores the query that caused the exception
	 *
	 * @var string
	 */
	protected $query = "";
	
	/**
	 * Constructs an exception
	 *
	 * @param string $message
	 * @param integer $errno
	 * @param string $query
	 * @param array $preTrace		A previously created backtrace
	 */
	public function __construct($message = null, $errno = 0, $query = "", $pretrace = null)
	{
		$this->backtrace = $pretrace;
		$this->query = $query;
		
		parent::__construct($message, $errno);
	}
	
	/**
	 * Converts the exception into a string
	 *
	 * @return string string representation of the exception
	 */
	public function __toString()
	{
		$result = "Database Exception:\n";
		$result .= $this->getMessage() . "\n";
		$result .= "Error number: " . $this->getCode() . "\n";
		$result .= "Query: " . $this->query . "\n";
		$result .= "Backtrace: " . print_r($this->getBacktrace(), true) . "\n\n";
		return $result;
	}

	/**
	 * Returns this exception's backtrace
	 *
	 * @return array backtrace
	 */
	public function getBacktrace()
	{
		if($this->backtrace)
		{
			return $this->backtrace;
		}
		else
		{
			return $this->getTrace();
		}
	}
	
	/**
	 * Returns this exception's query
	 *
	 * @return string query
	 */
	public function getQuery()
	{
		return $this->query;
	}
}
?>